# Generated by Django 2.2.5 on 2020-01-09 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_login_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_varified',
            new_name='email_verified',
        ),
    ]
