# Generated by Django 2.2.5 on 2020-02-01 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20200201_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='cleanlines',
            new_name='cleanliness',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='communications',
            new_name='communication',
        ),
    ]
